#!/usr/bin/env node

var fs = require('fs');
var coordinates = new Object();

fs.readFile(process.argv[2], function (err, data){
  if (err) throw err;
  var input = data.toString('ascii').split('\n');
  var i = 0;
  var c;
  
  for (var r = 0; r < input.length; r ++) {
    input[r] = input[r].split('');
    for (var c = 0; c <= input[r].length; c++){
      if (input[r][c]=='#'){
        coordinates[i] = {"row": r, "col": c };
        i++
      }
    }
  }

  createPath(coordinates, input);
  
 var tempBuffer=[];
  
  for(var x = 0; x<input.length-1; x++){
    tempBuffer += input[x].join('') + "\n"
  }

  fs.writeFile(process.argv[3], tempBuffer, function (err) {
      if (err) throw err;
    });
}); 

function createPath(coordinates, input){
  cLength = Object.keys(coordinates).length
  for(var index = 0; index < cLength - 1; index ++){
    startRow = coordinates[index].row;
    endRow = coordinates[index + 1].row;
    if (startRow > endRow){
      tempRow = startRow;
      startRow = endRow;
      endRow = tempRow;
    }
    for(c = startRow+1; c <= endRow; c++){
      input[c][coordinates[index].col] = '*'
    }

    startCol = coordinates[index].col;
    endCol = coordinates[index + 1].col;
    if (startCol > endCol){
      tempCol = startCol;
      startCol = endCol;
      endCol = tempCol;
    }

    var pathRow = coordinates[index+1].row
      for(r = startCol+1; r < endCol; r++){
      input[pathRow][r] = '*'
    }
  }
}

